<?php

namespace Escuela\UserManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleClassRepository extends BaseRepository
{
	
}
