escuela_core:
    resource: "@EscuelaCoreBundle/Resources/config/routing.yml"

escuela_commons:
    resource: "@EscuelaCommonsBundle/Resources/config/routing.yml"

escuela_user_manager:
    resource: "@EscuelaUserManagerBundle/Resources/config/routing.yml"