security:
    access_decision_manager:
        # Strategy can be: affirmative, unanimous or consensus
        strategy: unanimous
    acl:
        connection: local

        
    encoders:
        Escuela\UserManagerBundle\Entity\User:
                  algorithm:           sha512
                  encode_as_base64:    true
                  iterations:          5000

    #role_hierarchy:
     #   ROLE_ADMIN:       ROLE_USER
      #  ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                #class: Escuela\SoftOdontoBundle\Repository\UserRepository
                class: Escuela\UserManagerBundle\Entity\User
                property: username

    firewalls:
           
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/user/login$
            security: false
        
        recover:
            pattern: ^/admin/user/recover
            security: false
            
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: _security_check
                login_path: usermanager_homepage
                # if true, forward the user to the login form instead of redirecting
                #use_forward: false

                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            /
                #target_path_parameter:          _target_path
                #use_referer:                    false
            remember_me:
                key:      %secret%
                lifetime: 172800 # 2 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            logout:
               path:   usermanager_logout
               target: usermanager_homepage
               invalidate_session: false
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
        #- { path: ^/user/recover, roles: IS_AUTHENTICATED_ANONYMOUSLY}
